### ISSUE TITLE
I had expected env to support env variable substituion

### ISSUE THREAD

**Issue by blaggacao** [numtide/devshell#21]
https://github.com/numtide/devshell/blob/8850638db70cda50210a5152b1d555b9a520c8e0/default.nix#L66

I might miss a deeper reason, but as a naive user, I would have expected:

```nix
{

  env = {
    KUBECONFIG="$HOME/.kube/config";
  };

}
```

to work. Instead it evaluates to `$HOME/.kube/config` literally. Although the workaround is straight forward, I want to ensure with this issue it is intentional.

**work around**
```nix
{
  bash = {
    extra = ''
    export KUBECONFIG="$HOME/.kube/config"
    '';
  };
}

**Comment by zimbatm** [comment]
It's a good point, and also something that I have been wondering about. For now I opted for a safe default but my opinion can be changed.

Here are a few considerations that I have:

a. Key ordering is not guaranteed with TOML. This can be an issue if a user sets `FOO="something"` and `BAR="$FOO"` in the same file.
b. Escaping is not super clear to me. What happens if the user wants to have "$FOO" as the value? It seems like they might need a double backtick?
c. If we add support for other shells in the future, what does it mean for the value semantic? Will bash always be involved to setup the environment?

**Comment by zimbatm** [comment]
this is now supported:
```toml
[[env]]
name = "KUBECONFIG"
eval = "$HOME/.kubeconfig"
```
